name: check nonce
author: Kalle Lilja
description: Recursively scan a directory for `.html` files to ensure unique nonce values.

branding:
  color: green
  icon: code

inputs:
  directory:
    description: Directory to scan for .html files.
    required: false
    default: ${{ github.workspace }}
  continue-on-failure:
    description: Whether the workflow run should fail when unique nonce values are detected.
    required: false
    default: ${{ false }}

runs:
  using: "composite"
  steps:
    - name: Check for unique Nonce values (${{ inputs.directory }})
      run: |
        ls
        chmod +x "${{ github.action_path }}/check-nonce.sh"
        "${{ github.action_path }}/check-nonce.sh"
      shell: bash
      continue-on-error: ${{ inputs.continue-on-failure }}
      env:
        TARGET_DIRECTORY: ${{ inputs.directory }}
