name: setup-terraform
description: Install and Cache Terraform

inputs:
  terraform_version:
    description: The version of Terraform CLI to install.
    required: false
    default: '1.11.3' # https://github.com/hashicorp/terraform/releases
  terraform_wrapper:
    description: Install the wrapper for the `terraform` binary. Defaults to `true`.
    required: false
    default: ${{ true }}
  cache:
    description: Cache Terraform? Defaults to `true`.
    required: false
    default: ${{ true }}
  terraform_lock_file:
    description: Path to .terraform.lock.hcl used for cache. Defaults to `**/.terraform.lock.hcl`.
    required: false
    default: '**/.terraform.lock.hcl'

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: ${{ inputs.terraform_wrapper }}

    - name: Configure Terraform plugin cache
      if: ${{ inputs.cache }}
      shell: bash
      run: |
        # Set Terraform Cache Directory
        TF_PLUGIN_CACHE_DIR="${HOME}/.terraform.d/plugin-cache"
        mkdir --parents "${TF_PLUGIN_CACHE_DIR}"
        echo "TF_PLUGIN_CACHE_DIR=${TF_PLUGIN_CACHE_DIR}" >> "$GITHUB_ENV"

    - name: Cache Terraform
      if: ${{ inputs.cache }}
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ env.TF_PLUGIN_CACHE_DIR }}
        key: terraform-${{ runner.os }}-${{ hashFiles(inputs.terraform_lock_file) }}
        restore-keys: terraform-${{ runner.os }}-
