name: setup-hugo
description: Install and caches Hugo

inputs:
  hugo-version:
    description: Version of Hugo to install.
    required: false
    default: '0.145.0' # https://github.com/gohugoio/hugo/releases
  extended:
    description: Install Hugo extended?
    required: false
    default: ${{ true }}

runs:
  using: "composite"
  steps:
    - name: Setup Hugo
      id: setup_hugo
      uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
      with:
        hugo-version: ${{ inputs.hugo-version }}
        extended: ${{ inputs.extended }}

    - name: Cache Hugo modules
      if: steps.setup_hugo.outcome == 'success'
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ runner.temp }}/hugo_cache
        key: hugomod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
        restore-keys: hugomod-${{ runner.os }}-
