name: setup-hugo
description: Install and Cache Hugo

inputs:
  hugo-version:
    description: Version of Hugo to install.
    required: false
    default: '0.145.0' # https://github.com/gohugoio/hugo/releases
  hugo-cachedir:
    description: 'path to Hugo cache. Defaults to `${{ runner.temp }}/hugo_cache`.'
    required: false
    default: ''
  extended:
    description: Install Hugo extended?
    required: false
    default: ${{ true }}

runs:
  using: "composite"
  steps:
    - name: Set Hugo Cache Directory
      shell: bash
      run: |
        if [ -z "${{ inputs.hugo-cachedir }}" ]; then
          echo "HUGO_CACHEDIR=${{ runner.temp }}/hugo_cache" >> $GITHUB_ENV
        else
          echo "HUGO_CACHEDIR=${{ inputs.hugo-cachedir }}" >> $GITHUB_ENV
        fi

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
      with:
        hugo-version: ${{ inputs.hugo-version }}
        extended: ${{ inputs.extended }}

    - name: Cache Hugo modules
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ env.HUGO_CACHEDIR }}
        key: hugomod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
        restore-keys: hugomod-${{ runner.os }}-
