name: '🛡️ Code Scanning - schedule'

on:
  schedule:
    - cron: '17 22 * * 0' # Sunday 22:17
  workflow_dispatch:

jobs:
  codeql-analyze:
    name: CodeQL - Analyze (${{ matrix.language }})
    runs-on: 'ubuntu-latest'
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: actions
          build-mode: none
        - language: javascript-typescript
          build-mode: none

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Hugo
        if: matrix.language == 'javascript-typescript'
        uses: ./.github/actions/setup-hugo
        with:
          hugo-cachedir: ${{ runner.temp }}/hugo_cache

      - name: Initialize CodeQL
        uses: github/codeql-action/init@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          config-file: .github/codeql/codeql-config-${{ matrix.language }}.yml
      
      - name: Build with Hugo
        if: matrix.language == 'javascript-typescript'
        run: |
          hugo \
            --gc \
            --minify \
            --enableGitInfo \
            --baseURL "${URL}"
        shell: bash
        working-directory: web
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: Europe/Stockholm
          URL: "https://kallelilja.com"
          HUGO_PARAMS_gitCommit: 'codeql'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
        with:
          category: "/language:${{ matrix.language }}"
          output: sarif-results
          upload: failure-only

      - name: filter-sarif - javascript-typescript
        if: matrix.language == 'javascript-typescript'
        uses: advanced-security/filter-sarif@f3b8118a9349d88f7b1c0c488476411145b6270d # v1.0.1
        with:
          patterns: |
            -web/themes/hello-friend-ng/assets/js/prism.js:js/regex/missing-regexp-anchor
            -web/public/bundle.min.*.js:js/regex/missing-regexp-anchor
          input: "sarif-results/javascript.sarif"
          output: "sarif-results/${{ matrix.language }}.sarif"

      - name: Upload CodeQL sarif
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
        with:
          sarif_file: "sarif-results/${{ matrix.language }}.sarif"

  trivy:
    name: Trivy - fs
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Trivy
        uses: ./.github/actions/setup-trivy

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # v0.30.0
        with:
          cache: true
          hide-progress: true
          skip-setup-trivy: true
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy sarif
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
        with:
          sarif_file: 'trivy-results.sarif'
