name: '🩺 GitHub Actions - Continuous Integration (CI)'

on:
  pull_request:
    paths: 
      - '.github/{workflows,actions}workflows/**/*.{yml,yaml}'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gha-ci:
    name: 'GitHub Actions CI'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Actionlint
        uses: raven-actions/actionlint@01fce4f43a270a612932cb1c64d40505a029f821 # v2.0.0
        with:
          version: latest
          files: ".github/workflows/*.yaml, .github/workflows/*.yml"
          fail-on-error: true
          shellcheck: true
          pyflakes: true
          cache: true
          github-token: ${{ github.token }}
