name: '🚀 HUGO - Continuous Delivery (CD)'

on:
  push:
    branches:
      - main
    paths: 
      - 'web/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/hugo-ci.yaml
  
  build:
    needs: ci
    name: 'HUGO Build'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: web
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Save git sha
        id: git-sha
        run: echo "output=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Setup Hugo
        uses: ./.github/actions/setup-hugo
        with:
          cache: true
          hugo-cachedir: ${{ runner.temp }}/hugo_cache

      - name: Build with Hugo
        run: |
          hugo \
            --gc \
            --minify \
            --enableGitInfo \
            --baseURL "${URL}"
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: Europe/Stockholm
          URL: "https://kallelilja.com"
          HUGO_PARAMS_gitCommit: ${{ steps.git-sha.outputs.output }}

      - name: Check Hugo site for nonce errors
        uses: ./.github/actions/check-nonce
        with:
          directory: web/public

      - name: Add RSS Feed integrity
        run: |
          INTEGRITY_HASH=$(openssl dgst -sha384 -binary "public/index.xml" | openssl base64 -A)
          sed -z -i "s|<link rel=alternate type=application/rss+xml href=\([^\"]*\)/index.xml title=\"\([^\"]*\)\">|<link rel=alternate type=application/rss+xml href=\1/index.xml title=\"\2\" integrity=\"sha384-${INTEGRITY_HASH}\" crossorigin=\"anonymous\">|" "public/index.html"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: web/public

  deploy:
    needs: [ci, build]
    name: 'HUGO Deploy - Production'
    runs-on: ubuntu-latest

    environment: 
      name: production
      url: "https://kallelilja.com"

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
