name: '🚀 HUGO - Continuous Delivery (CD)'

on:
  push:
    branches:
      - main
    paths: 
      - 'web/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/hugo-ci.yaml
  
  build:
    needs: ci
    name: 'HUGO Build'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: web
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Save git sha
        id: git-sha
        run: echo "output=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Cache Hugo modules
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ runner.temp }}/hugo_cache
          key: hugomod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: hugomod-${{ runner.os }}-

      - name: Build with Hugo
        run: |
          hugo \
            --gc \
            --minify \
            --enableGitInfo \
            --baseURL "${URL}"
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: Europe/Stockholm
          URL: "https://kallelilja.com"
          HUGO_PARAMS_gitCommit: ${{ steps.git-sha.outputs.output }}
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: web/public

  deploy:
    needs: [ci, build]
    name: 'HUGO Deploy - Production'
    runs-on: ubuntu-latest

    environment: 
      name: production
      url: "https://kallelilja.com"

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
