name: OSV-Scanner Scheduled Scan

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "30 12 * * 1"
  workflow_dispatch:


permissions:
  actions: read
  contents: read
  security-events: write
  
jobs:
  scan-scheduled:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@764c91816374ff2d8fc2095dab36eecd42d61638 # v1.9.2
