name: 'Terraform'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: 
      - 'terraform/**'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_HTTP_PASSWORD: ${{ secrets.TF_HTTP_PASSWORD }}
      TF_VAR_tf_gh_token: ${{ secrets.TF_GH_TOKEN }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Imports
        run: | 
          terraform import github_repository.kallelilja_com kallelilja-com || echo "github_repository.kallelilja_com imported"
          terraform import github_branch.main kallelilja-com:main || echo "github_branch.main imported"
          terraform import github_repository_environment.production kallelilja-com:production || echo "github_repository_environment.production imported"
        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: terraform apply -auto-approve -input=false
