name: '🩺 Terraform - Continuous Integration (CI)'

on:
  pull_request:
    branches:
      - main
    paths: 
      - 'terraform/**.tf'
      - 'terraform/input/**'
  workflow_call:
    secrets:
      TF_STATE_TOKEN:
        required: true
      TF_GITHUB_TOKEN:
        required: true
      TF_STATUSCAKE_TOKEN:
        required: true
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-ci:
    name: 'Terraform CI'
    runs-on: ubuntu-latest
  
    defaults:
      run:
        shell: bash
        working-directory: terraform
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: ./.github/actions/setup-terraform
        with:
          cache: true
          terraform_lock_file: 'terraform/.terraform.lock.hcl'

      - name: Terraform Init
        run: |
          terraform init \
           -backend-config="password=${TF_STATE_TOKEN}"
        env:
          TF_STATE_TOKEN: ${{ secrets.TF_STATE_TOKEN }}
      
      - name: Terraform Validate
        run: terraform validate -no-tests

      - name: Terraform fmt -check
        run: terraform fmt -check -recursive

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        name: Cache TFLint plugins dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ runner.os }}-${{ hashFiles('terraform/.tflint.hcl') }}
          restore-keys: tflint-${{ runner.os }}-
  
      - uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4.1.1
        name: Setup TFLint
        with:
          tflint_version: v0.56.0 # https://github.com/terraform-linters/tflint/releases  tflint_linux_amd64.zip
          checksums: |-
            e0d74c557815ee51c6ecfe826ed62fd411ee6c10e1eab5532a0b0cc684c5db8a
  
      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
  
      - name: Run TFLint
        run: tflint -f compact

      - name: Set Trivy Version
        id: trivy_version
        run: echo "TRIVY_VERSION=v0.61.0" >> "$GITHUB_OUTPUT" # https://github.com/aquasecurity/trivy/releases

      - name: Setup Trivy vulnerability scanner
        uses: aquasecurity/setup-trivy@9ea583eb67910444b1f64abf338bd2e105a0a93d # v0.2.3
        with:
          cache: true
          version: ${{ steps.trivy_version.outputs.TRIVY_VERSION }}

      - name: Run Trivy vulnerability scanner in Terraform IaC mode
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # v0.30.0
        with:
          cache: true
          scan-type: 'config'
          scanners: 'terraform'
          hide-progress: true
          exit-code: '1'
          skip-setup-trivy: true
          skip-dirs: ".devcontainer"

      - name: Setup tfprovidercheck
        run: |
          set -e
          if [ ! -f tfprovidercheck.tar.gz ]; then
            curl -L -o tfprovidercheck.tar.gz ${TFPROVIDERCHECK_URL}
            echo "${TFPROVIDERCHECK_CHECKSUM}  tfprovidercheck.tar.gz" > tfprovidercheck.tar.gz.sha256
            sha256sum -c tfprovidercheck.tar.gz.sha256
          fi
          tar -xzf tfprovidercheck.tar.gz -C /usr/local/bin
        env:
          TFPROVIDERCHECK_URL: "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.4/tfprovidercheck_linux_amd64.tar.gz" # https://github.com/suzuki-shunsuke/tfprovidercheck/releases
          TFPROVIDERCHECK_CHECKSUM: "0adf02dcb8ca9ad07986f880347ebc348a73b850d8b8b8477b7fa5d5147c0b61"

      - name: Run tfprovidercheck
        run: |
          terraform version -json | tfprovidercheck

      - name: Terraform Plan
        id: terraform_plan
        run: terraform plan -input=false -no-color
        env:
          GITHUB_TOKEN:         ${{ secrets.TF_GITHUB_TOKEN }}
          STATUSCAKE_API_TOKEN: ${{ secrets.TF_STATUSCAKE_TOKEN }}

      - name: Summary
        run: |
          echo "$PLAN" >> $GITHUB_STEP_SUMMARY
        env:
          PLAN: "Terraform Plan\n${{ steps.terraform_plan.outputs.stdout }}"
