name: '🚀 Terraform - Continuous Delivery (CD)'

on:
  push:
    branches:
      - main
    paths: 
      - 'terraform/**.tf'
      - 'terraform/input/**'
  workflow_dispatch:
    inputs:
      do-apply:
        description: Perform `terraform apply` command?
        type: boolean
        required: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/terraform-ci.yaml
    secrets:
      TF_STATE_TOKEN:     ${{ secrets.TF_STATE_TOKEN }}
      TF_GITHUB_TOKEN:    ${{ secrets.TF_GITHUB_TOKEN }}

  deploy:
    needs: ci
    name: 'Terraform - Production'
    runs-on: ubuntu-latest

    environment:
      name: production

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="password=${TF_STATE_TOKEN}"
        env:
          TF_STATE_TOKEN: ${{ secrets.TF_STATE_TOKEN }}

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}

      - name: Terraform Apply
        id: terraform_Apply
        if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && github.event.inputs.do-apply == 'true')
        run: terraform apply -auto-approve -input=false
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
