name: '🩺 Terraform - Continuous Integration (CI)'

on:
  pull_request:
    branches:
      - main
    paths: 
      - 'terraform/**.tf'
      - 'terraform/input/**'
  workflow_call:
    secrets:
      TF_STATE_TOKEN:
        required: true
      TF_GITHUB_TOKEN:
        required: true
      TF_STATUSCAKE_TOKEN:
        required: true
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-ci:
    name: 'Terraform CI'
    runs-on: ubuntu-latest
  
    defaults:
      run:
        shell: bash
        working-directory: terraform
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Configure Terraform plugin cache
        run: |
          echo "TF_PLUGIN_CACHE_DIR=${HOME}/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
          mkdir --parents "${HOME}/.terraform.d/plugin-cache"

      - name: Cache Terraform
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('terraform/.terraform.lock.hcl') }}
          restore-keys: terraform-${{ runner.os }}-

      - name: Terraform Init
        run: |
          terraform init \
           -backend-config="password=${TF_STATE_TOKEN}"
        env:
          TF_STATE_TOKEN:   ${{ secrets.TF_STATE_TOKEN }}
      
      - name: Terraform Validate
        run: terraform validate -no-tests

      - name: Terraform fmt -check
        run: terraform fmt -check -recursive

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        name: Cache TFLint plugins dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ runner.os }}-${{ hashFiles('terraform/.tflint.hcl') }}
          restore-keys: tflint-${{ runner.os }}-
  
      - uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4.1.1
        name: Setup TFLint
        with:
          tflint_version: v0.55.1
          checksums: |-
            53379f38bc1e86c18885bfc85dc5fe2cd1f59729ae9a2afa16905189c1d67aa9
  
      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
  
      - name: Run TFLint
        run: tflint -f compact

      - name: Set Trivy Version
        id: trivy_version
        run: echo "TRIVY_VERSION=v0.60.0" >> "$GITHUB_OUTPUT"

      - name: Setup Trivy vulnerability scanner
        uses: aquasecurity/setup-trivy@ff1b8b060f23b650436d419b5e13f67f5d4c3087 # v0.2.2
        with:
          cache: true
          version: ${{ steps.trivy_version.outputs.TRIVY_VERSION }}

      - name: Run Trivy vulnerability scanner in Terraform IaC mode
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # v0.30.0
        with:
          cache: true
          scan-type: 'config'
          scanners: 'terraform'
          hide-progress: true
          exit-code: '1'
          skip-setup-trivy: true
          skip-dirs: ".devcontainer"

      - name: Setup tfprovidercheck
        run: |
          set -e
          if [ ! -f tfprovidercheck.tar.gz ]; then
            curl -L -o tfprovidercheck.tar.gz ${TFPROVIDERCHECK_URL}
            echo "${TFPROVIDERCHECK_CHECKSUM}  tfprovidercheck.tar.gz" > tfprovidercheck.tar.gz.sha256
            sha256sum -c tfprovidercheck.tar.gz.sha256
          fi
          tar -xzf tfprovidercheck.tar.gz -C /usr/local/bin
        env:
          TFPROVIDERCHECK_URL: "https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v1.0.3/tfprovidercheck_linux_amd64.tar.gz"
          TFPROVIDERCHECK_CHECKSUM: "8132aa60ba845307e3a1ae33421d368e5bc3ccb3e6546ac6a141c3a9c794c45c"

      - name: Run tfprovidercheck
        run: |
          terraform version -json | tfprovidercheck

      - name: Terraform Plan
        id: terraform_plan
        run: terraform plan -input=false -no-color
        env:
          GITHUB_TOKEN:         ${{ secrets.TF_GITHUB_TOKEN }}
          STATUSCAKE_API_TOKEN: ${{ secrets.TF_STATUSCAKE_TOKEN }}

      - name: Summary
        run: |
          echo "$PLAN" >> $GITHUB_STEP_SUMMARY
        env:
          PLAN: "Terraform Plan\n${{ steps.terraform_plan.outputs.stdout }}"
